version: 2
notify:
jobs:
  build:
    working_directory: ~/tacenda-web
    docker:
      - image: jdecode/php8-my-pg-node:ssl
    steps:
      - checkout
workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - build
