version: 2
jobs:
  build:
    working_directory: ~/noter
    docker:
      - image: jdecode/php8-my-pg-node
      - image: mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: docker
          MYSQL_DATABASE: noter
          MYSQL_USER: user
          MYSQL_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: Install Composer
          command: |
            composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
         name: Run test-cases
         command: vendor/bin/phpunit

workflows:
  version: 2
  validate-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: laravel-on-clouds
